/**
 * Environment Setup
 * Generates the .env file for the desktop (local) environment.
 */
import fs from 'fs'
import path from 'path'
import crypto from 'crypto'

/**
 * Generate or update the .env file for desktop mode.
 * @param {object} opts
 * @param {string} opts.projectRoot - Laravel project root
 * @param {number} opts.dbPort - MariaDB port
 * @param {number} opts.appPort - PHP server port
 * @param {string} opts.dbName - Database name
 */
export function setupDesktopEnv({ projectRoot, dbPort = 3307, appPort = 8100, dbName = 'portailrh_pnmls' }) {
    const envPath = path.join(projectRoot, '.env')
    const envBackup = path.join(projectRoot, '.env.web-backup')

    // Backup existing .env if it's a web env (not our desktop env)
    if (fs.existsSync(envPath)) {
        const existing = fs.readFileSync(envPath, 'utf-8')
        if (!existing.includes('APP_DESKTOP=true')) {
            fs.copyFileSync(envPath, envBackup)
        }
    }

    // Generate a stable APP_KEY if not already set
    let appKey = ''
    if (fs.existsSync(envPath)) {
        const match = fs.readFileSync(envPath, 'utf-8').match(/^APP_KEY=(.+)$/m)
        if (match && match[1]) appKey = match[1]
    }
    if (!appKey) {
        appKey = 'base64:' + crypto.randomBytes(32).toString('base64')
    }

    const envContent = `# ═══ Portail RH PNMLS - Desktop Environment ═══
# Auto-generated by Electron launcher. Do NOT edit manually.
APP_DESKTOP=true
APP_NAME="Portail RH PNMLS"
APP_ENV=local
APP_KEY=${appKey}
APP_DEBUG=false
APP_URL=http://127.0.0.1:${appPort}

# Online server for sync
SYNC_SERVER_URL=https://deeppink-rhinoceros-934330.hostingersite.com
SYNC_ENABLED=true
SYNC_INTERVAL_MINUTES=5

# Database (local MariaDB portable)
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=${dbPort}
DB_DATABASE=${dbName}
DB_USERNAME=root
DB_PASSWORD=

# Laravel internals
SESSION_DRIVER=database
QUEUE_CONNECTION=sync
CACHE_STORE=file
FILESYSTEM_DISK=local
LOG_CHANNEL=single

# Sanctum (local SPA)
SANCTUM_STATEFUL_DOMAINS=127.0.0.1:${appPort}
SESSION_DOMAIN=127.0.0.1

# Mail (disabled in desktop)
MAIL_MAILER=log
`

    fs.writeFileSync(envPath, envContent, 'utf-8')
    console.log(`[Env] Desktop .env written to ${envPath}`)
}

/**
 * Restore the web .env from backup (when switching back to web mode).
 */
export function restoreWebEnv(projectRoot) {
    const envPath = path.join(projectRoot, '.env')
    const envBackup = path.join(projectRoot, '.env.web-backup')

    if (fs.existsSync(envBackup)) {
        fs.copyFileSync(envBackup, envPath)
        console.log('[Env] Web .env restored from backup.')
    }
}
